blank_issues_enabled: false
contact_links:
  - name: 💬 GitHub Discussions
    url: https://github.com/semanticintent/semantic-d1-mcp/discussions
    about: Ask questions and discuss with the community
  - name: 🔒 Security Vulnerability
    url: https://github.com/semanticintent/semantic-d1-mcp/security/advisories/new
    about: Report security vulnerabilities privately
  - name: 📚 Documentation
    url: https://github.com/semanticintent/semantic-d1-mcp/blob/main/README.md
    about: Read the project documentation
